# Generated by Django 5.0.14 on 2026-01-18 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_at', models.DateTimeField()),
                ('arrival_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('base_price_cents', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='inventory.flight')),
            ],
            options={
                'indexes': [models.Index(fields=['flight', 'departure_at'], name='inventory_f_flight__50a400_idx'), models.Index(fields=['departure_at'], name='inventory_f_departu_3e4053_idx')],
            },
        ),
    ]
